### ISSUE TITLE
Allfo-kokous tunniste ei toimi

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Finto-suggestions#155]
Ko. tunnistetta on ehdotuksissa, mutta jos sen valitsee suodattimeksi, ei saa tulokseksi lainkaan viitteitä.

**Comment by ilona-x** [comment]
Ongelmana ilmeisesti tunnisteessa oleva väliviiva, sillä myöskään tekemäni testi-label -tunniste ei toimi.

**Comment by miguelahonen** [comment]
From now on tag labels with symbol (-) can be used in label names without harming the suggestion search listing. 

The problem was in the SuggestionFiltering.vue at line 10:
_str = str.concat('\b', this.tags[indexes[i]].label.toLowerCase());_
\b (backspace) is better delimiter than previous '-'
The delimiter '-' caused the problem with label names including '-'

Also _values = value.split('-')_ was changed to _values = value.split('\b')_ in the utils.py at line 33
